version: "3"

tasks:
  brew-dump:
    desc: Generate new Brewfile
    cmds:
      - brew bundle dump --brews --taps --casks --force

  install:
    desc: Install all dotfiles
    cmds:
      - find . -name ".DS_Store" -type f -delete
      - mkdir -p $HOME/.config $HOME/.zsh
      - stow -R -v -d . -t $HOME home
      - stow -R -v -d . -t $HOME/.config config
      - stow -R -v -d . -t $HOME/.zsh zsh
